title: "Grand Hotel Construction Project"
description: "Official information hub for the Grand Hotel construction project. Providing updates to all stakeholders."
baseurl: "/hotel-construction-project" # IMPORTANT: If your site is hosted at github.io/repo-name
url: "https://DrinkCoff.github.io" # Your full GitHub Pages URL (without baseurl)
timezone: America/New_York # Or your project's timezone (e.g., America/Chicago, America/Los_Angeles)

# Jekyll theme (Minima is default, can change later)
theme: minima

# Exclude folders that Jekyll shouldn't process
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Collections (optional, for organized content like progress reports)
collections:
  progress_reports:
    output: true
    permalink: /progress/:name/ # /progress/report-date/
  pages: # ADD THIS NEW COLLECTION FOR YOUR _pages directory
    output: true # This tells Jekyll to generate actual HTML files for these pages
    permalink: /:name/ # This sets the URL structure (e.g., /drawings/, /permits/)